# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $POSTGRES_PORT:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
