import type { Student, Project } from "..";
import { generateTeams } from "..";

const studentData: Student[] = [

    { id: "1", name: "Alice Smith", major: "CS", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Epsilon: Smart Home Integration" },
    { id: "2", name: "Bob Johnson", major: "ME", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "3", name: "Carol Lee", major: "BME", seniority: "Freshman", choices: ["Project Beta: Medical Imaging System", "Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device" },
    { id: "4", name: "David Brown", major: "EE", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "5", name: "Ella Garcia", major: "CS", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "6", name: "Frank Harris", major: "ME", seniority: "Freshman", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System" },
    { id: "7", name: "Grace Adams", major: "CS", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device" },
    { id: "8", name: "Henry Wilson", major: "CE", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor" },
    { id: "9", name: "Ivy Young", major: "DS", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration" },
    { id: "10", name: "Jack Martinez", major: "Systems", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
  
    { id: "11", name: "Kara Patel", major: "SE", seniority: "Sophomore", choices: ["Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "12", name: "Leo Nguyen", major: "BME", seniority: "Sophomore", choices: ["Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration, Project Delta: Autonomous Vehicle Sensor" },
    { id: "13", name: "Mia Robinson", major: "CS", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device" },
    { id: "14", name: "Nate Carter", major: "ME", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration" },
    { id: "15", name: "Olivia Gomez", major: "EE", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis" },
    { id: "16", name: "Paul Sanders", major: "CS", seniority: "Sophomore", choices: ["Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },
    { id: "17", name: "Quinn Allen", major: "Systems", seniority: "Sophomore", choices: ["Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "18", name: "Rachel Bell", major: "BME", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device" },
    { id: "19", name: "Sam Cook", major: "CE", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "20", name: "Tina Diaz", major: "DS", seniority: "Sophomore", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },

    { id: "21", name: "Uma Lewis", major: "BME", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration, Project Delta: Autonomous Vehicle Sensor" },
    { id: "22", name: "Victor Wright", major: "ME", seniority: "Junior", choices: ["Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "23", name: "Wendy Green", major: "CS", seniority: "Junior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration" },
    { id: "24", name: "Xander Hughes", major: "EE", seniority: "Junior", choices: ["Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "25", name: "Yara Howard", major: "BME", seniority: "Junior", choices: ["Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device" },
    { id: "26", name: "Zane Ward", major: "ME", seniority: "Junior", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "27", name: "Ava Cooper", major: "CS", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Epsilon: Smart Home Integration" },
    { id: "28", name: "Ben Price", major: "BME", seniority: "Junior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "29", name: "Cara Collins", major: "CS", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "30", name: "Drew Barnes", major: "EE", seniority: "Junior", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
  
    { id: "31", name: "Eli Ross", major: "CE", seniority: "Senior", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "32", name: "Fay Jenkins", major: "CS", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device" },
    { id: "33", name: "Gus Myers", major: "BME", seniority: "Senior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis" },
    { id: "34", name: "Hana Warren", major: "CS", seniority: "Senior", choices: ["Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System" },
    { id: "35", name: "Ian Barnes", major: "ME", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device" },
    { id: "36", name: "Jade Kim", major: "CS", seniority: "Senior", choices: ["Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration" },
    { id: "37", name: "Kai Lawson", major: "DS", seniority: "Senior", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System" },
    { id: "38", name: "Lily Paul", major: "EE", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device" },
    { id: "39", name: "Max Rivera", major: "ME", seniority: "Senior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System" },
    { id: "40", name: "Nina Phillips", major: "BME", seniority: "Senior", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },

    { id: "41", name: "Olivia Parker", major: "EE", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "42", name: "Paul Rogers", major: "BME", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "43", name: "Quinn Martinez", major: "CS", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "44", name: "Rachel Diaz", major: "DS", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System" },
    { id: "45", name: "Samuel Lewis", major: "ME", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device" },
    { id: "46", name: "Tina Wilson", major: "CS", seniority: "Sophomore", choices: ["Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "47", name: "Uma Thomas", major: "BME", seniority: "Sophomore", choices: ["Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration" },
    { id: "48", name: "Victor Scott", major: "EE", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device" },
    { id: "49", name: "Wendy Collins", major: "ME", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "50", name: "Xavier Young", major: "CS", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
  
    { id: "51", name: "Yasmine Price", major: "DS", seniority: "Freshman", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "52", name: "Zachary Hernandez", major: "BME", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device" },
    { id: "53", name: "Alice Perez", major: "CS", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "54", name: "Bobby Sanders", major: "EE", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration" },
    { id: "55", name: "Caroline Cooper", major: "ME", seniority: "Freshman", choices: ["Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis" },
    { id: "56", name: "Dylan Adams", major: "CS", seniority: "Freshman", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device" },
    { id: "57", name: "Ella Clark", major: "BME", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "58", name: "Finn Rodriguez", major: "EE", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "59", name: "Grace White", major: "CS", seniority: "Freshman", choices: ["Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration" },
    { id: "60", name: "Henry Lewis", major: "ME", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },

    { id: "61", name: "Isabella Bell", major: "CS", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Epsilon: Smart Home Integration" },
    { id: "62", name: "Jack Lopez", major: "BME", seniority: "Junior", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "63", name: "Karen Hughes", major: "EE", seniority: "Junior", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "3200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "64", name: "Liam Simmons", major: "ME", seniority: "Junior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "65", name: "Mia Ramirez", major: "CS", seniority: "Junior", choices: ["Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },
    { id: "66", name: "Noah Patel", major: "DS", seniority: "Junior", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device" },
    { id: "67", name: "Olivia Green", major: "BME", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration" },
    { id: "68", name: "Peter Adams", major: "ME", seniority: "Junior", choices: ["Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "69", name: "Quinn Black", major: "CS", seniority: "Junior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "70", name: "Ruby James", major: "EE", seniority: "Junior", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
  
    { id: "71", name: "Sarah Coleman", major: "ME", seniority: "Sophomore", choices: ["Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "72", name: "Thomas Long", major: "CS", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device" },
    { id: "73", name: "Ursula Reed", major: "DS", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System, Project Epsilon: Smart Home Integration" },
    { id: "74", name: "Victor White", major: "CS", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device" },
    { id: "75", name: "Wanda King", major: "EE", seniority: "Sophomore", choices: ["Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "76", name: "Xander Torres", major: "ME", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "77", name: "Yara Ortiz", major: "BME", seniority: "Sophomore", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
    { id: "78", name: "Zane Bell", major: "CS", seniority: "Sophomore", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "79", name: "Aaron Hughes", major: "EE", seniority: "Sophomore", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "80", name: "Bella Carter", major: "ME", seniority: "Sophomore", choices: ["Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },
  
    { id: "81", name: "Cameron Morgan", major: "CS", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "82", name: "Daniel Sanders", major: "BME", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "83", name: "Eva Perez", major: "EE", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "84", name: "Frankie Lee", major: "ME", seniority: "Freshman", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "85", name: "Gabby Kim", major: "CS", seniority: "Freshman", choices: ["Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor" },
    { id: "86", name: "Henry Barnes", major: "DS", seniority: "Freshman", choices: ["Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis" },
    { id: "87", name: "Ivy Fisher", major: "BME", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration" },
    { id: "88", name: "Jacob Ramirez", major: "EE", seniority: "Freshman", choices: ["Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "89", name: "Kylie Hall", major: "ME", seniority: "Freshman", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System" },
    { id: "90", name: "Lily Torres", major: "CS", seniority: "Freshman", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor" },
  
    { id: "91", name: "Mason Nguyen", major: "BME", seniority: "Senior", choices: ["Project Epsilon: Smart Home Integration", "Project Beta: Medical Imaging System", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Beta: Medical Imaging System, Project Alpha: Data Science Analysis" },
    { id: "92", name: "Nina Baker", major: "CS", seniority: "Senior", choices: ["Project Gamma: Renewable Energy Device", "Project Delta: Autonomous Vehicle Sensor", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Gamma: Renewable Energy Device, Project Delta: Autonomous Vehicle Sensor, Project Alpha: Data Science Analysis" },
    { id: "93", name: "Oscar Wright", major: "ME", seniority: "Senior", choices: ["Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System" },
    { id: "94", name: "Piper Walker", major: "EE", seniority: "Senior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "95", name: "Quincy Allen", major: "DS", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Beta: Medical Imaging System", "Project Delta: Autonomous Vehicle Sensor"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Beta: Medical Imaging System, Project Delta: Autonomous Vehicle Sensor" },
    { id: "96", name: "Rachel Evans", major: "BME", seniority: "Senior", choices: ["Project Epsilon: Smart Home Integration", "Project Gamma: Renewable Energy Device", "Project Alpha: Data Science Analysis"], class: "2200", choicesString: "Project Epsilon: Smart Home Integration, Project Gamma: Renewable Energy Device, Project Alpha: Data Science Analysis" },
    { id: "97", name: "Samuel Turner", major: "CS", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Delta: Autonomous Vehicle Sensor", "Project Gamma: Renewable Energy Device"], class: "3200", choicesString: "Project Alpha: Data Science Analysis, Project Delta: Autonomous Vehicle Sensor, Project Gamma: Renewable Energy Device" },
    { id: "98", name: "Tara Foster", major: "ME", seniority: "Senior", choices: ["Project Beta: Medical Imaging System", "Project Gamma: Renewable Energy Device", "Project Epsilon: Smart Home Integration"], class: "2200", choicesString: "Project Beta: Medical Imaging System, Project Gamma: Renewable Energy Device, Project Epsilon: Smart Home Integration" },
    { id: "99", name: "Uma Mitchell", major: "EE", seniority: "Senior", choices: ["Project Delta: Autonomous Vehicle Sensor", "Project Epsilon: Smart Home Integration", "Project Alpha: Data Science Analysis"], class: "3200", choicesString: "Project Delta: Autonomous Vehicle Sensor, Project Epsilon: Smart Home Integration, Project Alpha: Data Science Analysis" },
    { id: "100", name: "Vince Carter", major: "CS", seniority: "Senior", choices: ["Project Alpha: Data Science Analysis", "Project Gamma: Renewable Energy Device", "Project Beta: Medical Imaging System"], class: "2200", choicesString: "Project Alpha: Data Science Analysis, Project Gamma: Renewable Energy Device, Project Beta: Medical Imaging System" }
  


 
];

const projectData: Project[] = [
  { id: "1", name: "Project Alpha: Data Science Analysis", type: "SW" },
  { id: "2", name: "Project Beta: Medical Imaging System", type: "SW" },
  { id: "3", name: "Project Gamma: Renewable Energy Device", type: "HW" },
  { id: "4", name: "Project Delta: Autonomous Vehicle Sensor", type: "HW" },
  { id: "5", name: "Project Epsilon: Smart Home Integration", type: "Both" },
];

// Displaying dummy data to check
console.log("Dummy Student Data:", studentData);
console.log("\nDummy Project Data:", projectData);
console.log("\nTeams:");
console.log(generateTeams(studentData, projectData));
